on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - 3.11.0-alpha.2
        - 3.10.0
        - 3.9.9
        - 3.9.8
        - 3.9.7
        - 3.9.6
        - 3.9.5
        - 3.9.4
        - 3.9.3
        - 3.9.2
        - 3.9.1
        - 3.9.0
        - 3.8.12
        - 3.8.11
        - 3.8.10
        - 3.8.9
        - 3.8.8
        - 3.8.7
        - 3.8.6
        - 3.8.5
        - 3.8.4
        - 3.8.3
        - 3.8.2
        - 3.8.1
        - 3.8.0
        - 3.7.12
        - 3.7.11
        - 3.7.10
        - 3.7.9
        - 3.7.8
        - 3.7.7
        - 3.7.6
        - 3.7.5
        - 3.7.1
        - 3.6.15
        - 3.6.14
        - 3.6.13
        - 3.6.12
        - 3.6.11
        - 3.6.10
        - 3.6.9
        - 3.6.8
        - 3.6.7
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install structlog 21.3.0
        run: pip install structlog==21.3.0
      - name: Test structlog with python -OO
        run: python -OO test.py
